package com.example.sengstudio1a.model;

public class Donor {

    private final String firstName;
    private final String lastName;
    private final String email;
    private final String phone;

    public Donor(String firstName, String lastName, String email, String phone) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
    }

}


//
//public class Donor {
//
//    private final String firstName;
//    private final String lastName;
//    private final String phone;
//    private final String email;
////    private final String password;
//
//    /**
//     * Create a new Donor using the given parameters. The unique userID
//     * is generated by Firebase.
//     */
//    public Donor(String firstName, String lastName, String email, String phone,
//                 String password) {
//        this.firstName = firstName;
//        this.lastName = lastName;
//        this.email = email;
//        this.phone = phone;
////        this.password = password;
//    }
//
//    // public Review[] getReviews()
//
//    // public Booking[] getBookings()
//
//    // public Booking[] getDonationHistory()
//
//}
